# Generated by Django 3.1.12 on 2025-07-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSmear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blood_smears/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.CharField(max_length=100)),
                ('confiance', models.FloatField(blank=True, default=0, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frottis', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explication', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('frottis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='diagnostics.bloodsmear')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='patients.patient')),
            ],
        ),
    ]
