# Generated by Django 3.1.12 on 2025-04-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsmear',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
    ]
