# Generated by Django 3.1.12 on 2025-04-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('taille', models.FloatField()),
                ('poids', models.FloatField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='patients_photos/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientImage',
        ),
    ]
